
-- ============================================================================
-- TechCity - Fase 6 (Oracle PL/SQL)
-- Setup completo em ORDEM DE EXECUÇÃO única (pode rodar tudo de uma vez).
-- Objetos criados: USERS, OCORRENCIAS, ALERTAS, RELATORIOS_OCORRENCIAS_LOG,
--                  SEQUENCE relatorios_ocorrencias_log_seq,
--                  FUNCTIONS fn_total_ocorrencias, fn_resumo_ocorrencia,
--                  PROCEDURES pr_registrar_alerta, pr_relatorio_ocorrencias_usuario
-- ============================================================================

SET SERVEROUTPUT ON;

-------------------------------------------------------------------------------
-- 0) LIMPEZA (DROP SE EXISTIREM) - seguro para reexecução
-------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE pr_relatorio_ocorrencias_usuario'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE pr_registrar_alerta'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_resumo_ocorrencia'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_total_ocorrencias'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE relatorios_ocorrencias_log_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE relatorios_ocorrencias_log CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE alertas CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ocorrencias CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-------------------------------------------------------------------------------
-- 1) TABELAS BASE
-------------------------------------------------------------------------------
-- USERS
CREATE TABLE users (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username  VARCHAR2(100) NOT NULL,
  role      VARCHAR2(20)  DEFAULT 'USER' CHECK (role IN ('USER','ADMIN','GESTOR')),
  ativo     CHAR(1)       DEFAULT 'S' CHECK (ativo IN ('S','N'))
);

CREATE UNIQUE INDEX ux_users_username ON users(username);

-- OCORRENCIAS
CREATE TABLE ocorrencias (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    NUMBER NOT NULL,
  titulo     VARCHAR2(255) NOT NULL,
  descricao  CLOB,
  data       TIMESTAMP DEFAULT SYSTIMESTAMP,
  status     VARCHAR2(30) DEFAULT 'ABERTA',
  CONSTRAINT fk_ocorr_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX ix_ocorr_user ON ocorrencias(user_id, data DESC);

-- ALERTAS
CREATE TABLE alertas (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ocorrencia_id     NUMBER NOT NULL,
  nivel_criticidade VARCHAR2(20),
  data_alerta       TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_alerta_ocorr FOREIGN KEY (ocorrencia_id) REFERENCES ocorrencias(id)
);

-------------------------------------------------------------------------------
-- 2) TABELA DE LOG + SEQUENCE (como especificado)
-------------------------------------------------------------------------------
CREATE TABLE relatorios_ocorrencias_log (
  id               NUMBER PRIMARY KEY,
  user_id          NUMBER NOT NULL,
  qtd_ocorrencias  NUMBER,
  ultima_data      TIMESTAMP,
  ultima_titulo    VARCHAR2(255),
  data_execucao    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_log_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE SEQUENCE relatorios_ocorrencias_log_seq START WITH 1 INCREMENT BY 1;

-------------------------------------------------------------------------------
-- 3) DADOS EXEMPLO (opcionais para teste)
-------------------------------------------------------------------------------
INSERT INTO users (username, role, ativo) VALUES ('maria.oliveira', 'USER', 'S');
INSERT INTO users (username, role, ativo) VALUES ('eduarda.brito', 'ADMIN', 'S');
INSERT INTO users (username, role, ativo) VALUES ('matheus.sousa', 'GESTOR', 'S');
INSERT INTO users (username, role, ativo) VALUES ('egon.silva', 'USER', 'S');

-- Ocorrências para user_id 1 (maria)
INSERT INTO ocorrencias (user_id, titulo, descricao, status) VALUES (1, 'Sistema fora do ar', 'Falha geral na aplicação da área central', 'ABERTA');
INSERT INTO ocorrencias (user_id, titulo, descricao, status) VALUES (1, 'Iluminação pública', 'Poste apagado na Rua A, altura do nº 200', 'ABERTA');

-- Ocorrência para user_id 2 (eduarda)
INSERT INTO ocorrencias (user_id, titulo, descricao, status) VALUES (2, 'Coleta de resíduos', 'Acúmulo de lixo na Praça Central', 'ABERTA');

COMMIT;

-------------------------------------------------------------------------------
-- 4) FUNCTIONS
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_total_ocorrencias (
    p_user_id IN NUMBER
) RETURN NUMBER
IS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_total
      FROM ocorrencias
     WHERE user_id = p_user_id;

    RETURN v_total;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;  -- Nenhuma ocorrência encontrada
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro ao calcular total de ocorrências: ' || SQLERRM);
        RETURN -1;  -- Indica erro
END;
/
SHOW ERRORS FUNCTION fn_total_ocorrencias;

CREATE OR REPLACE FUNCTION fn_resumo_ocorrencia (
    p_ocorr_id IN NUMBER
) RETURN VARCHAR2
IS
    v_resumo VARCHAR2(100);
BEGIN
    SELECT SUBSTR(descricao, 1, 100) || '...'
      INTO v_resumo
      FROM ocorrencias
     WHERE id = p_ocorr_id;

    RETURN v_resumo;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Ocorrência não encontrada';
    WHEN OTHERS THEN
        RETURN 'Erro ao gerar resumo: ' || SQLERRM;
END;
/
SHOW ERRORS FUNCTION fn_resumo_ocorrencia;

-------------------------------------------------------------------------------
-- 5) PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE pr_registrar_alerta (
    p_ocorr_id IN NUMBER,
    p_criticidade IN VARCHAR2
)
IS
BEGIN
    INSERT INTO alertas (ocorrencia_id, nivel_criticidade, data_alerta)
    VALUES (p_ocorr_id, p_criticidade, SYSTIMESTAMP);

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro ao registrar alerta: ' || SQLERRM);
END;
/
SHOW ERRORS PROCEDURE pr_registrar_alerta;

CREATE OR REPLACE PROCEDURE pr_relatorio_ocorrencias_usuario (
    p_user_id         IN NUMBER,
    p_qtd_ocorrencias OUT NUMBER,
    p_ultima_data     OUT TIMESTAMP,
    p_ultima_titulo   OUT VARCHAR2
)
IS
BEGIN
    -- Contar o total de ocorrências do usuário
    SELECT COUNT(*)
      INTO p_qtd_ocorrencias
      FROM ocorrencias
     WHERE user_id = p_user_id;

    -- Buscar a ocorrência mais recente
    SELECT data, titulo
      INTO p_ultima_data, p_ultima_titulo
      FROM (
        SELECT data, titulo
          FROM ocorrencias
         WHERE user_id = p_user_id
         ORDER BY data DESC
      )
     WHERE ROWNUM = 1;

    -- Gravar o log do relatório
    INSERT INTO relatorios_ocorrencias_log (
        id, user_id, qtd_ocorrencias, ultima_data, ultima_titulo
    ) VALUES (
        relatorios_ocorrencias_log_seq.NEXTVAL,
        p_user_id,
        p_qtd_ocorrencias,
        p_ultima_data,
        p_ultima_titulo
    );

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_qtd_ocorrencias := 0;
        p_ultima_data := NULL;
        p_ultima_titulo := NULL;
        DBMS_OUTPUT.PUT_LINE('Nenhuma ocorrência encontrada para o usuário ' || p_user_id);

    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Erro ao gerar relatório: ' || SQLERRM);
END pr_relatorio_ocorrencias_usuario;
/
SHOW ERRORS PROCEDURE pr_relatorio_ocorrencias_usuario;

-------------------------------------------------------------------------------
-- 6) TESTES RÁPIDOS (opcionais)
-------------------------------------------------------------------------------
PROMPT === Teste: Functions ===
SELECT u.username, fn_total_ocorrencias(u.id) AS total_ocorrencias
  FROM users u
 ORDER BY 2 DESC;

SELECT o.id, o.titulo, fn_resumo_ocorrencia(o.id) AS resumo
  FROM ocorrencias o
 ORDER BY o.data DESC;

PROMPT === Teste: Procedures ===
DECLARE
  v_qtd NUMBER;
  v_data TIMESTAMP;
  v_titulo VARCHAR2(255);
BEGIN
  -- Gera relatório para user_id = 1
  pr_relatorio_ocorrencias_usuario(1, v_qtd, v_data, v_titulo);
  DBMS_OUTPUT.PUT_LINE('Total de ocorrências: ' || v_qtd);
  DBMS_OUTPUT.PUT_LINE('Última data: ' || v_data);
  DBMS_OUTPUT.PUT_LINE('Último título: ' || v_titulo);

  -- Registra alerta crítico para a primeira ocorrência do user 1 (se existir)
  pr_registrar_alerta(1, 'ALTO');
END;
/
SELECT * FROM alertas ORDER BY data_alerta DESC;
SELECT * FROM relatorios_ocorrencias_log ORDER BY data_execucao DESC;

-- Fim do script
