-- db/deploy/02_triggers.sql
SET DEFINE OFF;

CREATE OR REPLACE TRIGGER trg_auditoria_alertas
AFTER INSERT ON ALERTAS
FOR EACH ROW
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
  v_user_id NUMBER;
  v_id      NUMBER;
BEGIN
  BEGIN
    SELECT USER_ID INTO v_user_id FROM OCORRENCIAS WHERE ID = :NEW.OCORRENCIA_ID;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN v_user_id := NULL;
  END;

  SELECT RELATORIOS_OCORRENCIAS_LOG_SEQ.NEXTVAL INTO v_id FROM dual;

  INSERT INTO RELATORIOS_OCORRENCIAS_LOG(
    ID, USER_ID, QTD_OCORRENCIAS, ULTIMA_DATA, ULTIMA_TITULO, DATA_EXECUCAO, DATA_REGISTRO, MENSAGEM, FONTE
  )
  VALUES(
    v_id, v_user_id, 1, SYSTIMESTAMP, SUBSTR(:NEW.MENSAGEM,1,255), SYSTIMESTAMP, SYSTIMESTAMP,
    'Alerta inserido: '||:NEW.NIVEL_CRITICIDADE, 'trg_auditoria_alertas'
  );

  COMMIT;
END;
/
