INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (USERS_SEQ.NEXTVAL, 'teste', '1234');
INSERT INTO OCORRENCIAS(ID, TITULO, DATA_CRIACAO, USER_ID, DATA_OCORRENCIA, DESCRICAO) 
VALUES (OCORRENCIAS_SEQ.NEXTVAL, 'Ocorrência teste', SYSDATE, 1, SYSDATE, 'Descrição teste');
COMMIT;
