-- Usuários do sistema
CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);

-- Perfis de usuário
CREATE TABLE USER_ROLES (
    USER_ID NUMBER REFERENCES USERS(ID),
    ROLE VARCHAR2(50) NOT NULL
);

-- Ocorrências
CREATE TABLE OCORRENCIAS (
    ID NUMBER PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    USER_ID NUMBER REFERENCES USERS(ID),
    DATA DATE,
    DESCRICAO VARCHAR2(400),
    DATA_OCORRENCIA DATE
);

-- Alertas relacionados às ocorrências
CREATE TABLE ALERTAS (
    ID NUMBER PRIMARY KEY,
    OCORRENCIA_ID NUMBER REFERENCES OCORRENCIAS(ID),
    NIVEL_CRITICIDADE VARCHAR2(20),
    MENSAGEM VARCHAR2(400),
    DATA_ALERTA DATE DEFAULT SYSDATE
);

-- Log de relatórios de ocorrências por usuário
CREATE TABLE RELATORIOS_OCORRENCIAS_LOG (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER REFERENCES USERS(ID),
    QTD_OCORRENCIAS NUMBER,
    ULTIMA_DATA DATE,
    ULTIMA_TITULO VARCHAR2(100),
    DATA_EXECUCAO DATE DEFAULT SYSDATE,
    DATA_REGISTRO DATE DEFAULT SYSDATE
);

-- =========================
-- SEQUENCES
-- =========================

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OCORRENCIAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALERTAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RELATORIOS_OCORRENCIAS_LOG_SEQ START WITH 1 INCREMENT BY 1;

-- =========================
-- DADOS DE TESTE
-- =========================

-- Usuário de teste
INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (USERS_SEQ.NEXTVAL, 'teste', '1234');

-- Ocorrência de teste
INSERT INTO OCORRENCIAS(
    ID, TITULO, DATA_CRIACAO, USER_ID, DATA, DESCRICAO, DATA_OCORRENCIA
) VALUES (
    OCORRENCIAS_SEQ.NEXTVAL,
    'Ocorrência teste',
    SYSDATE,
    1,
    SYSDATE,
    'Descrição de teste',
    SYSDATE
);

-- Alerta de teste
INSERT INTO ALERTAS(
    ID, OCORRENCIA_ID, NIVEL_CRITICIDADE, MENSAGEM, DATA_ALERTA
) VALUES (
    ALERTAS_SEQ.NEXTVAL,
    1,
    'ALTO',
    'Alerta teste inicial',
    SYSDATE
);

-- Relatório de teste
INSERT INTO RELATORIOS_OCORRENCIAS_LOG(
    ID, USER_ID, QTD_OCORRENCIAS, ULTIMA_DATA, ULTIMA_TITULO, DATA_EXECUCAO, DATA_REGISTRO
) VALUES (
    RELATORIOS_OCORRENCIAS_LOG_SEQ.NEXTVAL,
    1,
    1,
    SYSDATE,
    'Ocorrência teste',
    SYSDATE,
    SYSDATE
);

COMMIT;